### PR TITLE
Convert aws/prepare script to improved format

### PR DESCRIPTION
**Pull request by zaksoup**
Core bosh needs this change in order to run our CI. Currently we're pointing to my fork and would like to point to the canonical repo.

### CODE REVIEW

**Comment by zaksoup** [comment]
@cfdreddbot @ljfranklin I'm p sure I should be covered by Pivotal's CLA? My membership of what I remember to be the relevant orgs is public.

**Comment by ljfranklin** [comment]
@zaksoup cool, we'll get this merged. Doesn't look like your memberships are public though:
screen shot 2016-11-17 at 2 56 54 pm

**Comment by cdutra** [comment]
@zaksoup The PR removed the `SSLIP_IO_KEY` which is making our pipeline (https://bosh-cpi.ci.cf-app.com/teams/main/pipelines/certify-aws?groups=certify-aws) fail.
The `missing inputs: environment` error is on our end. We need to add the terraform resource.

**Comment by zaksoup** [comment]
@cdutra I understand how this is breaking you but not what I can do to fix this. Do you want me to add SSLIP_IO_KEY back, or is this a change you're informing me that you plan to make when you merge? How can I help?

@ljfranklin funny, I thought for sure I had made those public. I'll fix immediately.

Love,
Zak

**Comment by zaksoup** [comment]
cla all good wooooo

**Comment by ljfranklin** [comment]
@zaksoup As nifty as @cunnie's sslip.io service is, we should probably move away from passing his private key around if we want to consider these scripts re-usable :) That said, our Director still needs a valid SSL cert for us to use the Golang CLI and I'm assuming BATs will eventually require this as well. Seems like we have a couple options to get this pipeline green:

**Better long term:** Update PR to generate self-signed SSL certs. CA Cert could either be stored in LastPass and passed in or also generated and passed along as a task output.

**Quick and dirty:** Update PR to make `SSL_CERT` and `SSL_KEY` required environment variables and store an actual SSL cert in LastPass. While this unblocks the CPI pipeline, this probably won't work for most people unless they buy wildcard certs and setup some extra DNS plumping.

What do you think @zaksoup?

**Comment by zaksoup** [comment]
@ljfranklin let's do the long term thing. I think setting up these scripts to auto-generate the correct certs for one-time-use is the way to go.

**Comment by cunnie** [comment]
I think we [BOSH CPI] should close this PR, re-work it, and re-submit it.

- it's a few months old
- it has conflicts

The goal seems to replace CloudFormation with Terraform, and we should continue on that line. Also scrap the sslip.io key and generate a key. Also use bosh-deployment to generate director and key.

It appears that we're not even using this fork. Comments @zaksoup @cdutra ?

**Comment by zaksoup** [comment]
I'm closing this. it's been so long I don't even remember what's going on and *I was the one who created this PR to begin with*. whoops

**Pull request closed without merging**
